version: '3.8'

networks:
  swaLab_network:
    driver: bridge

services:
  db_container:
    image: postgres:latest
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - swaLab_network

  backend_container:
    build:
      context: ./BackEnd
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    depends_on:
      - db_container
    networks:
      - swaLab_network

  frontend_container:
    build:
      context: ./FrontEnd
    environment:
      REACT_APP_BACKEND_URL: http://backend_container:80
    ports:
      - "3000:80"
    depends_on:
      - backend_container
    networks:
      - swaLab_network