# Use the official Node.js image as the base image
FROM node:14 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./FrontEnd/package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining application code to the container
COPY ./FrontEnd ./

# Build the application
RUN npm run build

# Use the official Nginx image as the runtime image
FROM nginx:alpine

# Copy the build output from the build image to the Nginx image
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the host
EXPOSE 80

# Command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]
